import _ from 'lodash'

import { testOnly } from '../../helpers/scope'
import { ADDRESS_ONE, ADDRESS_ZERO, RouterInterface } from '../../helpers/types'
import { SwapTestParamsV3, testSwap } from '../testSwap.v3.spec'
import {
  CONSTRUCTOR_PARAMS,
  DEX,
  DODO,
  findDexName,
  TOKENS,
  VYPER_CONFIG,
  WALLETS,
} from './constants'

const TESTS: Array<SwapTestParamsV3> = [
  {
    // only: true,
    walletAddr: WALLETS.WHALE1,
    amountIn: 1,
    amountOutMin: 0.001,
    srcTokenData: TOKENS.USDT,
    dstTokenData: TOKENS.AVAX,
    isSourceFee: false,
    isRouterSource: false,
    routes: [
      {
        fromToken: TOKENS.USDT.address,
        toToken: TOKENS.WAVAX.address,
        from: ADDRESS_ONE,
        to: ADDRESS_ZERO,
        lpAddress: '0xe28984e1ee8d431346d32bec9ec800efb643eef4',
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.PANGOLIN,
        dexInterface: RouterInterface.UNISWAP_V2,
        part: 100000000,
        amountAfterFee: 9970,
        order: '0x',
      },
    ],
  },
  {
    // only: true,
    walletAddr: WALLETS.WHALE1,
    amountIn: 1,
    amountOutMin: 50,
    srcTokenData: TOKENS.AVAX,
    dstTokenData: TOKENS.USDT,
    isSourceFee: false,
    isRouterSource: true,
    routes: [
      {
        fromToken: TOKENS.WAVAX.address,
        toToken: TOKENS.USDT.address,
        from: ADDRESS_ZERO,
        to: ADDRESS_ZERO,
        lpAddress: '0xe28984e1ee8d431346d32bec9ec800efb643eef4',
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.PANGOLIN,
        dexInterface: RouterInterface.UNISWAP_V2,
        part: 100000000,
        amountAfterFee: 9970,
        order: '0x',
      },
    ],
  },
  {
    // only: true,
    walletAddr: WALLETS.WHALE1,
    amountIn: 1,
    amountOutMin: 0.1,
    srcTokenData: TOKENS.USDT,
    dstTokenData: TOKENS.PNG,
    isSourceFee: false,
    isRouterSource: false,
    routes: [
      {
        fromToken: TOKENS.USDT.address,
        toToken: TOKENS.PNG.address,
        from: ADDRESS_ONE,
        to: ADDRESS_ZERO,
        lpAddress: '0x1ffb6ffc629f5d820dcf578409c2d26a2998a140',
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.PANGOLIN,
        dexInterface: RouterInterface.UNISWAP_V2,
        part: 100000000,
        amountAfterFee: 9970,
        order: '0x',
      },
    ],
  },
  {
    // only: true,
    walletAddr: WALLETS.WHALE1,
    amountIn: 1,
    amountOutMin: 0.1,
    srcTokenData: TOKENS.USDT,
    dstTokenData: TOKENS.USDCe,
    isSourceFee: false,
    isRouterSource: false,
    routes: [
      {
        fromToken: TOKENS.USDT.address,
        toToken: TOKENS.USDCe.address,
        from: ADDRESS_ONE,
        to: ADDRESS_ZERO,
        lpAddress: '0xc13e562d92f7527c4389cd29c67dabb0667863ea',
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.PANGOLIN,
        dexInterface: RouterInterface.UNISWAP_V2,
        part: 100000000,
        amountAfterFee: 9970,
        order: '0x',
      },
    ],
  },
  {
    // only: true,
    walletAddr: WALLETS.WHALE1,
    amountIn: 1,
    amountOutMin: 0.001,
    srcTokenData: TOKENS.USDT,
    dstTokenData: TOKENS.AVAX,
    isSourceFee: false,
    isRouterSource: false,
    routes: [
      {
        fromToken: TOKENS.USDT.address,
        toToken: TOKENS.WAVAX.address,
        from: ADDRESS_ONE,
        to: ADDRESS_ZERO,
        lpAddress: '0xed8cbd9f0ce3c6986b22002f03c6475ceb7a6256',
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.TRADERJOE,
        dexInterface: RouterInterface.UNISWAP_V2,
        part: 100000000,
        amountAfterFee: 9970,
        order: '0x',
      },
    ],
  },
  {
    // only: true,
    walletAddr: WALLETS.WHALE1,
    amountIn: 1,
    amountOutMin: 50,
    srcTokenData: TOKENS.AVAX,
    dstTokenData: TOKENS.USDT,
    isSourceFee: false,
    isRouterSource: true,
    routes: [
      {
        fromToken: TOKENS.WAVAX.address,
        toToken: TOKENS.USDT.address,
        from: ADDRESS_ZERO,
        to: ADDRESS_ZERO,
        lpAddress: '0xed8cbd9f0ce3c6986b22002f03c6475ceb7a6256',
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.TRADERJOE,
        dexInterface: RouterInterface.UNISWAP_V2,
        part: 100000000,
        amountAfterFee: 9970,
        order: '0x',
      },
    ],
  },
  {
    // only: true,
    walletAddr: WALLETS.WHALE1,
    amountIn: 1,
    amountOutMin: 0.9,
    srcTokenData: TOKENS.USDT,
    dstTokenData: TOKENS.USDCe,
    isSourceFee: false,
    isRouterSource: false,
    routes: [
      {
        fromToken: TOKENS.USDT.address,
        toToken: TOKENS.USDCe.address,
        from: ADDRESS_ONE,
        to: ADDRESS_ZERO,
        lpAddress: '0x2e02539203256c83c7a9f6fa6f8608a32a2b1ca2',
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.TRADERJOE,
        dexInterface: RouterInterface.UNISWAP_V2,
        part: 100000000,
        amountAfterFee: 9970,
        order: '0x',
      },
    ],
  },
  {
    // only: true,
    walletAddr: WALLETS.WHALE1,
    amountIn: 1,
    amountOutMin: 0.001,
    srcTokenData: TOKENS.USDT,
    dstTokenData: TOKENS.AVAX,
    isSourceFee: false,
    isRouterSource: false,
    routes: [
      {
        fromToken: TOKENS.USDT.address,
        toToken: TOKENS.WAVAX.address,
        from: ADDRESS_ONE,
        to: ADDRESS_ZERO,
        lpAddress: '0x5fc70cf6a4a858cf4124013047e408367eba1ace',
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.LYDIA,
        dexInterface: RouterInterface.UNISWAP_V2,
        part: 100000000,
        amountAfterFee: 9970,
        order: '0x',
      },
    ],
  },
  {
    // only: true,
    walletAddr: WALLETS.WHALE1,
    amountIn: 1,
    amountOutMin: 50,
    srcTokenData: TOKENS.AVAX,
    dstTokenData: TOKENS.USDT,
    isSourceFee: false,
    isRouterSource: true,
    routes: [
      {
        fromToken: TOKENS.WAVAX.address,
        toToken: TOKENS.USDT.address,
        from: ADDRESS_ZERO,
        to: ADDRESS_ZERO,
        lpAddress: '0x5fc70cf6a4a858cf4124013047e408367eba1ace',
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.LYDIA,
        dexInterface: RouterInterface.UNISWAP_V2,
        part: 100000000,
        amountAfterFee: 9970,
        order: '0x',
      },
    ],
  },

  // SOURCE FEE

  {
    // only: true,
    walletAddr: WALLETS.WHALE1,
    amountIn: 1,
    amountOutMin: 0.001,
    srcTokenData: TOKENS.USDT,
    dstTokenData: TOKENS.AVAX,
    isSourceFee: true,
    isRouterSource: false,
    routes: [
      {
        fromToken: TOKENS.USDT.address,
        toToken: TOKENS.WAVAX.address,
        from: ADDRESS_ONE,
        to: ADDRESS_ZERO,
        lpAddress: '0xe28984e1ee8d431346d32bec9ec800efb643eef4',
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.PANGOLIN,
        dexInterface: RouterInterface.UNISWAP_V2,
        part: 100000000,
        amountAfterFee: 9970,
        order: '0x',
      },
    ],
  },
  {
    // only: true,
    walletAddr: WALLETS.WHALE1,
    amountIn: 1,
    amountOutMin: 50,
    srcTokenData: TOKENS.AVAX,
    dstTokenData: TOKENS.USDT,
    isSourceFee: true,
    isRouterSource: true,
    routes: [
      {
        fromToken: TOKENS.WAVAX.address,
        toToken: TOKENS.USDT.address,
        from: ADDRESS_ZERO,
        to: ADDRESS_ONE,
        lpAddress: '0xe28984e1ee8d431346d32bec9ec800efb643eef4',
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.PANGOLIN,
        dexInterface: RouterInterface.UNISWAP_V2,
        part: 100000000,
        amountAfterFee: 9970,
        order: '0x',
      },
    ],
  },
  {
    // only: true,
    walletAddr: WALLETS.WHALE1,
    amountIn: 1,
    amountOutMin: 0.1,
    srcTokenData: TOKENS.USDT,
    dstTokenData: TOKENS.PNG,
    isSourceFee: true,
    isRouterSource: false,
    routes: [
      {
        fromToken: TOKENS.USDT.address,
        toToken: TOKENS.PNG.address,
        from: ADDRESS_ONE,
        to: ADDRESS_ONE,
        lpAddress: '0x1ffb6ffc629f5d820dcf578409c2d26a2998a140',
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.PANGOLIN,
        dexInterface: RouterInterface.UNISWAP_V2,
        part: 100000000,
        amountAfterFee: 9970,
        order: '0x',
      },
    ],
  },
  {
    // only: true,
    walletAddr: WALLETS.WHALE1,
    amountIn: 1,
    amountOutMin: 0.1,
    srcTokenData: TOKENS.USDT,
    dstTokenData: TOKENS.USDCe,
    isSourceFee: true,
    isRouterSource: false,
    routes: [
      {
        fromToken: TOKENS.USDT.address,
        toToken: TOKENS.USDCe.address,
        from: ADDRESS_ONE,
        to: ADDRESS_ONE,
        lpAddress: '0xc13e562d92f7527c4389cd29c67dabb0667863ea',
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.PANGOLIN,
        dexInterface: RouterInterface.UNISWAP_V2,
        part: 100000000,
        amountAfterFee: 9970,
        order: '0x',
      },
    ],
  },
  {
    // only: true,
    walletAddr: WALLETS.WHALE1,
    amountIn: 1,
    amountOutMin: 0.001,
    srcTokenData: TOKENS.USDT,
    dstTokenData: TOKENS.AVAX,
    isSourceFee: true,
    isRouterSource: false,
    routes: [
      {
        fromToken: TOKENS.USDT.address,
        toToken: TOKENS.WAVAX.address,
        from: ADDRESS_ONE,
        to: ADDRESS_ZERO,
        lpAddress: '0xed8cbd9f0ce3c6986b22002f03c6475ceb7a6256',
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.TRADERJOE,
        dexInterface: RouterInterface.UNISWAP_V2,
        part: 100000000,
        amountAfterFee: 9970,
        order: '0x',
      },
    ],
  },
  {
    // only: true,
    walletAddr: WALLETS.WHALE1,
    amountIn: 1,
    amountOutMin: 50,
    srcTokenData: TOKENS.AVAX,
    dstTokenData: TOKENS.USDT,
    isSourceFee: true,
    isRouterSource: true,
    routes: [
      {
        fromToken: TOKENS.WAVAX.address,
        toToken: TOKENS.USDT.address,
        from: ADDRESS_ZERO,
        to: ADDRESS_ONE,
        lpAddress: '0xed8cbd9f0ce3c6986b22002f03c6475ceb7a6256',
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.TRADERJOE,
        dexInterface: RouterInterface.UNISWAP_V2,
        part: 100000000,
        amountAfterFee: 9970,
        order: '0x',
      },
    ],
  },
  {
    // only: true,
    walletAddr: WALLETS.WHALE1,
    amountIn: 1,
    amountOutMin: 0.9,
    srcTokenData: TOKENS.USDT,
    dstTokenData: TOKENS.USDCe,
    isSourceFee: true,
    isRouterSource: false,
    routes: [
      {
        fromToken: TOKENS.USDT.address,
        toToken: TOKENS.USDCe.address,
        from: ADDRESS_ONE,
        to: ADDRESS_ONE,
        lpAddress: '0x2e02539203256c83c7a9f6fa6f8608a32a2b1ca2',
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.TRADERJOE,
        dexInterface: RouterInterface.UNISWAP_V2,
        part: 100000000,
        amountAfterFee: 9970,
        order: '0x',
      },
    ],
  },
  {
    // only: true,
    walletAddr: WALLETS.WHALE1,
    amountIn: 1,
    amountOutMin: 0.001,
    srcTokenData: TOKENS.USDT,
    dstTokenData: TOKENS.AVAX,
    isSourceFee: true,
    isRouterSource: false,
    routes: [
      {
        fromToken: TOKENS.USDT.address,
        toToken: TOKENS.WAVAX.address,
        from: ADDRESS_ONE,
        to: ADDRESS_ZERO,
        lpAddress: '0x5fc70cf6a4a858cf4124013047e408367eba1ace',
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.LYDIA,
        dexInterface: RouterInterface.UNISWAP_V2,
        part: 100000000,
        amountAfterFee: 9970,
        order: '0x',
      },
    ],
  },
  {
    // only: true,
    walletAddr: WALLETS.WHALE1,
    amountIn: 1,
    amountOutMin: 50,
    srcTokenData: TOKENS.AVAX,
    dstTokenData: TOKENS.USDT,
    isSourceFee: true,
    isRouterSource: true,
    routes: [
      {
        fromToken: TOKENS.WAVAX.address,
        toToken: TOKENS.USDT.address,
        from: ADDRESS_ZERO,
        to: ADDRESS_ONE,
        lpAddress: '0x5fc70cf6a4a858cf4124013047e408367eba1ace',
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.LYDIA,
        dexInterface: RouterInterface.UNISWAP_V2,
        part: 100000000,
        amountAfterFee: 9970,
        order: '0x',
      },
    ],
  },

  {
    // only: true,
    walletAddr: WALLETS.WHALE1,
    amountIn: 1,
    amountOutMin: 50,
    srcTokenData: TOKENS.AVAX,
    dstTokenData: TOKENS.USDT,
    isSourceFee: true,
    isRouterSource: true,
    routes: [
      {
        fromToken: TOKENS.WAVAX.address,
        toToken: TOKENS.USDT.address,
        from: ADDRESS_ZERO,
        to: ADDRESS_ONE,
        lpAddress: '0x5fc70cf6a4a858cf4124013047e408367eba1ace',
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.LYDIA,
        dexInterface: RouterInterface.UNISWAP_V2,
        part: 100000000,
        amountAfterFee: 9970,
        order: '0x',
      },
    ],
  },
  {
    // only: true,
    walletAddr: '0x0000023cbc437683aec074e3cb75ad38ae2e87e1',
    srcTokenData: TOKENS.AVAX,
    dstTokenData: TOKENS.MIM,
    amountIn: 0.01,
    amountOutMin: 1,
    isSourceFee: false,
    isRouterSource: true,
    routes: [
      {
        routerAddress: '0xe54ca86531e17ef3616d22ca28b0d458b6c89106',
        lpAddress: '0x363d093d419093998c06a4f422d73a43156d7f3e',
        fromToken: '0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7',
        toToken: '0x488f73cddda1de3664775ffd91623637383d6404',
        from: '0x0000000000000000000000000000000000000000',
        to: '0x676fb7b87059c2f8e3809f3ba3bce64fd79a2177',
        part: 100000000,
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        amountAfterFee: 9970,
        order: '0x',
        dexInterface: 0,
      },
      {
        routerAddress: '0x262dcfb36766c88e6a7a2953c16f8defc40c378a',
        lpAddress: '0x676fb7b87059c2f8e3809f3ba3bce64fd79a2177',
        fromToken: '0x488f73cddda1de3664775ffd91623637383d6404',
        toToken: '0xd1c3f94de7e5b45fa4edbba472491a9f4b166fc4',
        from: '0x363d093d419093998c06a4f422d73a43156d7f3e',
        to: '0xf13f00d79449afb7351c8f0cd61ea2249c925185',
        part: 100000000,
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        amountAfterFee: 9970,
        order: '0x',
        dexInterface: 0,
      },
      {
        routerAddress: '0x60ae616a2155ee3d9a68541ba4544862310933d4',
        lpAddress: '0xf13f00d79449afb7351c8f0cd61ea2249c925185',
        fromToken: '0xd1c3f94de7e5b45fa4edbba472491a9f4b166fc4',
        toToken: '0xcc2f1d827b18321254223df4e84de399d9ff116c',
        from: '0x676fb7b87059c2f8e3809f3ba3bce64fd79a2177',
        to: '0xf46ae03f4968003b9b127883a3c54d0979f7f909',
        part: 100000000,
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        amountAfterFee: 9970,
        order: '0x',
        dexInterface: 0,
      },
      {
        routerAddress: '0x60ae616a2155ee3d9a68541ba4544862310933d4',
        lpAddress: '0xf46ae03f4968003b9b127883a3c54d0979f7f909',
        fromToken: '0xcc2f1d827b18321254223df4e84de399d9ff116c',
        toToken: '0x130966628846bfd36ff31a822705796e8cb8c18d',
        from: '0xf13f00d79449afb7351c8f0cd61ea2249c925185',
        to: '0x0000000000000000000000000000000000000000',
        part: 100000000,
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        amountAfterFee: 9970,
        order: '0x',
        dexInterface: 0,
      },
    ],
  },

  // kyberDMM
  {
    // only: true,
    walletAddr: WALLETS.WHALE1,
    amountIn: 1,
    amountOutMin: 40,
    srcTokenData: TOKENS.AVAX,
    dstTokenData: TOKENS.USDCe,
    isSourceFee: true,
    isRouterSource: true,
    routes: [
      {
        fromToken: TOKENS.WAVAX.address,
        toToken: TOKENS.USDCe.address,
        from: ADDRESS_ZERO,
        to: ADDRESS_ONE,
        lpAddress: '0x475d13a015d478aa8271655584348f3268007cbd',
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.KYBER_DMM,
        dexInterface: RouterInterface.KYBER_DMM,
        part: 100000000,
        amountAfterFee: 10000,
        order: '0x',
      },
    ],
  },
  {
    // only: true,
    walletAddr: WALLETS.WHALE1,
    amountIn: 1,
    amountOutMin: 0.002,
    srcTokenData: TOKENS.USDCe,
    dstTokenData: TOKENS.AVAX,
    isSourceFee: false,
    isRouterSource: false,
    routes: [
      {
        fromToken: TOKENS.USDCe.address,
        toToken: TOKENS.WAVAX.address,
        from: ADDRESS_ONE,
        to: ADDRESS_ZERO,
        lpAddress: '0x475d13a015d478aa8271655584348f3268007cbd',
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.KYBER_DMM,
        dexInterface: RouterInterface.KYBER_DMM,
        part: 100000000,
        amountAfterFee: 10000,
        order: '0x',
      },
    ],
  },
  {
    // only: true,
    walletAddr: WALLETS.WHALE1,
    amountIn: 1,
    amountOutMin: 40,
    srcTokenData: TOKENS.AVAX,
    dstTokenData: TOKENS.USDT,
    isSourceFee: false,
    isRouterSource: true,
    routes: [
      {
        fromToken: TOKENS.WAVAX.address,
        toToken: TOKENS.USDCe.address,
        from: ADDRESS_ZERO,
        to: '0x108695e4e46e8232efebe63c421cc302cc780d45',
        lpAddress: '0x475d13a015d478aa8271655584348f3268007cbd',
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.KYBER_DMM,
        dexInterface: RouterInterface.KYBER_DMM,
        part: 100000000,
        amountAfterFee: 10000,
        order: '0x',
      },
      {
        fromToken: TOKENS.USDCe.address,
        toToken: TOKENS.USDT.address,
        from: '0x475d13a015d478aa8271655584348f3268007cbd',
        to: ADDRESS_ZERO,
        lpAddress: '0x108695e4e46e8232efebe63c421cc302cc780d45',
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.KYBER_DMM,
        dexInterface: RouterInterface.KYBER_DMM,
        part: 100000000,
        amountAfterFee: 10000,
        order: '0x',
      },
    ],
  },
  {
    // isSourceFee = false && stopLimitFee > minimumStopLimitFee && super split paths
    // only: true,
    walletAddr: WALLETS.WHALE1,
    amountIn: 1,
    amountOutMin: 10,
    srcTokenData: TOKENS.WAVAX,
    dstTokenData: TOKENS.USDCe,
    isSourceFee: false,
    isRouterSource: true,
    routes: [
      {
        fromToken: TOKENS.WAVAX.address,
        toToken: TOKENS.WBTCE.address,
        from: ADDRESS_ZERO,
        to: ADDRESS_ZERO,
        lpAddress: DEX.WOO_FI,
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.WOO_FI,
        dexInterface: RouterInterface.WOO_FI,
        part: 100000000,
        amountAfterFee: 10000,
        order: '0x',
      },
      {
        fromToken: TOKENS.WBTCE.address,
        toToken: TOKENS.USDCe.address,
        from: ADDRESS_ZERO,
        to: ADDRESS_ZERO,
        lpAddress: '0x62475f52add016a06b398aa3b2c2f2e540d36859',
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.TRADERJOE,
        dexInterface: RouterInterface.UNISWAP_V2,
        part: 100000000,
        amountAfterFee: 9970,
        order: '0x',
      },
    ],
  },
  {
    // isSourceFee = false && stopLimitFee > minimumStopLimitFee && super split paths
    // only: true,
    walletAddr: WALLETS.WHALE1,
    amountIn: 1,
    amountOutMin: 10,
    srcTokenData: TOKENS.AVAX,
    dstTokenData: TOKENS.USDC,
    isSourceFee: false,
    isRouterSource: true,
    routes: [
      {
        fromToken: TOKENS.WAVAX.address,
        toToken: TOKENS.USDC.address,
        from: ADDRESS_ZERO,
        to: ADDRESS_ZERO,
        lpAddress: DEX.WOO_FI,
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.WOO_FI,
        dexInterface: RouterInterface.WOO_FI,
        part: 100000000,
        amountAfterFee: 10000,
        order: '0x',
      },
    ],
  },
  {
    // isSourceFee = false && stopLimitFee > minimumStopLimitFee && super split paths
    // only: true,
    walletAddr: WALLETS.WHALE2,
    amountIn: 1,
    amountOutMin: 0.01,
    srcTokenData: TOKENS.USDC,
    dstTokenData: TOKENS.AVAX,
    isSourceFee: false,
    isRouterSource: true,
    routes: [
      {
        fromToken: TOKENS.USDC.address,
        toToken: TOKENS.WAVAX.address,
        from: ADDRESS_ZERO,
        to: ADDRESS_ZERO,
        lpAddress: DEX.WOO_FI,
        direction: 0,
        fromTokenIndex: 0,
        toTokenIndex: 0,
        routerAddress: DEX.WOO_FI,
        dexInterface: RouterInterface.WOO_FI,
        part: 100000000,
        amountAfterFee: 10000,
        order: '0x',
      },
    ],
  },
]

testOnly('avalanche', 'swap', () =>
  describe.only('Swap v3', () => {
    testSwap(
      TESTS,
      findDexName,
      CONSTRUCTOR_PARAMS,
      WALLETS.WHALE1,
      WALLETS.FEE
    )
  })
)
